openapi: 3.0.0
info:
  title: quicargo-test
  description: hiring test for quicargo
  version: 1.0.0

paths:
  /trucks/{id}:
    put:
      summary: Update the system about truck information
      operationId: updateTrucks
      tags:
        - truck
      parameters:
        - name: carrier_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: truck_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Truck data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Truck'
      responses:
        204:
          description: Truck has been updated successfully
        404:
          description: not found

  /carriers/{carrier_id}/trucks:
    post:
      summary: Get all available trucks within radius of pickup point
      operationId: getAvailableTrucks
      tags:
        - truck
      parameters:
        - name: carrier_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Order data
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        200:
          description: trucks received successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
components:
  schemas:
    Order:
      type: object
      properties:
        radius:
          type: number
        route:
          type: object
          properties:
            pickup:
              $ref: '#/components/schemas/Location'
            delivery:
              $ref: '#/components/schemas/Location'
        cargo_weight:
          type: number
        cargo_amount:
          type: number
      example:
        radius: 2
        cargo_weight: 200.00
        cargo_amount: 100
        route:
          pickup:
            lng: 4.895168
            lat: 52.370216
          delivery:
            lng: 4.895168
            lat: 52.370216

    Location:
      type: object
      properties:
        lat:
          type: number
        lng:
          type: number

    Truck:
      type: object
      properties:
        lng:
          type: number
        lat:
          type: number
        license_plate:
          type: string
        max_weight:
          type: number
        current_weight:
          type: number
        max_pallets:
          type: number
        current_pallets:
          type: number
        carrier_id:
          type: number
      example:
        lng: 4.895168
        lat: 52.370216
        licensplate: "234ASF"
        max_weight: 1000.00
        current_weight: 500.00
        max_pallets: 200
        current_pallets: 150
        carrier_id: 1
